# java/.tmux-init.conf
# Force-restart the 'editor' window
tmux respawn-window -k -t "$SESSION:editor" "exec $bash_path"

# Start devenv shell (this boots the PG 18 service in the background)
tmux send-keys -t "$SESSION:editor" "devenv shell" C-m
# Give the JDK and Postgres an extra moment to initialize
sleep 2
tmux send-keys -t "$SESSION:editor" "nvim-java" C-m

# Force-restart 'console' window
tmux respawn-window -k -t "$SESSION:console" "exec $bash_path"
tmux send-keys -t "$SESSION:console" "devenv shell" C-m
sleep 2
tmux send-keys -t "$SESSION:console" "clear" C-m
tmux send-keys -t "$SESSION:console" "fastfetch" C-m

# Create the server window
tmux new-window -t "$SESSION" -n "server" -c "$selected_path" "exec $bash_path"
tmux send-keys -t "$SESSION:server" "devenv shell" C-m
sleep 2
tmux send-keys -t "$SESSION:server" "clear" C-m
tmux send-keys -t "$SESSION:server" "mvn spring-boot:run" C-m

# Raising postgres service
tmux new-window -t "$SESSION" -n "services" -c "$selected_path" "exec $bash_path"
tmux send-keys -t "$SESSION:services" "devenv up" C-m

# Give Postgres time to fully boot up and run initial scripts
sleep 4

# This creates a new window specifically for pgcli
tmux new-window -t "$SESSION" -n "database" -c "$selected_path" "exec $bash_path"
tmux send-keys -t "$SESSION:database" "devenv shell" C-m
sleep 3
# Automatically connect to the database created in devenv.nix
tmux send-keys -t "$SESSION:database" "clear" C-m
tmux send-keys -t "$SESSION:database" 'pgcli "postgresql://$database_username:$database_password@$database_host:$database_port/$database_name"' C-m

tmux swap-window -d -s "$SESSION:database" -t "$SESSION:lazygit"
tmux swap-window -d -s "$SESSION:services" -t "$SESSION:lazygit"

# Focus the editor
tmux select-window -t "$SESSION:editor"
